version: '3.8'

services:
  backend:
    image: sfuentes005/lb-101-form-app:backend
    container_name: LB-101-Form-Backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URL=${MONGODB_URL}

  frontend:
    image: sfuentes005/lb-101-form-app:frontend
    container_name: LB-101-Form-Frontend
    ports:
      - "80:80"
    depends_on:
      - backend